### ISSUE TITLE
Users who are confirmed not a member to any association are undetected

### ISSUE THREAD

**Issue by DutcherNL** [DutcherNL/Scala-Dining-WebApp#155] opened 2019-08-03 20:38 UTC
And thus face no repercussions.

**Comment by DutcherNL** [comment] 2019-08-03 20:41
I am currently writing a suspension protocol in the locked users branch that automatically disables a lot of abusable rights when members are not a member of any association. It can also be used to limit functionality of users who misbehaved if neccessary (hopefully never neccessary).
Currently implemented adjustments:
Suspended users can do nothing on the dining list except: sign up/off if their balance remains positive (or they are part of Q's special arrangement)
Users can not comment to dining lists either or adjust their allergies (to prevent abusive or trolling remarks).

**Comment by mhvis** [comment] 2023-03-07 15:45
I'll close this for staleness. The issue is currently not present that I know of. When users without association join dining lists or post comments, that will not go unnoticed.

Reopen it if necessary.

**Closed by mhvis** 2023-03-07 15:45 UTC
Labels: administration-maintenance
